application:
    environment: prod
    language: en
    editor: vim
    temp: /tmp
    develop: 'false'
    command: about
    checked: 'true'
    remote:
        user: root
        port: 22
        console: /usr/local/bin/drupal
        keys:
            public: ~/.ssh/id_rsa.pub
            private: ~/.ssh/id_rsa
            passphrase: ~/.ssh/passphrase.txt
