stages:
  - test

.test_template: &test_definition
  stage: test
  script:
    - uname -a
    - docker ps
    - docker run hello-world

ubuntu1804distro:
  <<: *test_definition
  tags:
    - ubuntu1804distro

ubuntu1804upstream:
  <<: *test_definition
  tags:
    - ubuntu1804upstream

ubuntu2004distro:
  <<: *test_definition
  tags:
    - ubuntu2004distro

ubuntu2004upstream:
  <<: *test_definition
  tags:
    - ubuntu2004upstream

rhel7distro:
  <<: *test_definition
  tags:
    - rhel7distro

rhel7upstream:
  <<: *test_definition
  tags:
    - rhel7upstream

rhel8distro:
  <<: *test_definition
  tags:
    - rhel8distro

rhel8upstream:
  <<: *test_definition
  tags:
    - rhel8upstream

centos7distro:
  <<: *test_definition
  tags:
    - centos7distro

centos7upstream:
  <<: *test_definition
  tags:
    - centos7upstream

centos8distro:
  <<: *test_definition
  tags:
    - centos8distro

centos8upstream:
  <<: *test_definition
  tags:
    - centos8upstream

archdistro:
  <<: *test_definition
  tags:
    - archdistro

windows_server:
  <<: *test_definition
  tags:
    - windows_server

windows_1:
  <<: *test_definition
  tags:
    - windows_1
