stages:
  - build
  - test

variables:
  BOWLINE_IMAGE_PREFIX: "$CI_REGISTRY/"
  BOWLINE_IMAGE_SUFFIX: "/ci:$CI_COMMIT_SHA"

default:
  before_script:
    - echo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  image: docker:19.03.13
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t "${BOWLINE_IMAGE_PREFIX}civicactions/bowline${BOWLINE_IMAGE_SUFFIX}" .
    - docker push "${BOWLINE_IMAGE_PREFIX}civicactions/bowline${BOWLINE_IMAGE_SUFFIX}"

.test_template: &linux_test_definition
  stage: test
  script:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
    - sudo chmod +x /usr/bin/docker-compose
    - bash --login -i ./tests/test.sh
    - bash --login --posix -i ./tests/test.sh
    - command -v dash && dash ./tests/test.sh || echo "Skipping dash"
    - zsh --login --interactive ./tests/test.sh
    - mksh -li ./tests/test.sh


ubuntu1804distro:
  <<: *linux_test_definition
  tags:
    - ubuntu1804distro

ubuntu1804upstream:
  <<: *linux_test_definition
  tags:
    - ubuntu1804upstream

ubuntu2004distro:
  <<: *linux_test_definition
  tags:
    - ubuntu2004distro

ubuntu2004upstream:
  <<: *linux_test_definition
  tags:
    - ubuntu2004upstream

rhel7distro:
  <<: *linux_test_definition
  tags:
    - rhel7distro

rhel7upstream:
  <<: *linux_test_definition
  tags:
    - rhel7upstream

rhel8distro:
  <<: *linux_test_definition
  tags:
    - rhel8distro

rhel8upstream:
  <<: *linux_test_definition
  tags:
    - rhel8upstream

centos7distro:
  <<: *linux_test_definition
  tags:
    - centos7distro

centos7upstream:
  <<: *linux_test_definition
  tags:
    - centos7upstream

centos8distro:
  <<: *linux_test_definition
  tags:
    - centos8distro

centos8upstream:
  <<: *linux_test_definition
  tags:
    - centos8upstream

archdistro:
  <<: *linux_test_definition
  tags:
    - archdistro

windowsserver:
  variables:
    BOWLINE_IMAGE_SUFFIX: "$CI_COMMIT_SHA"
  script:
    - \"$env:ProgramFiles\git\usr\bin\bash.exe\" -O expand_aliases ./tests/test.sh
    - set PATH=C:\tools\cygwin\bin;%PATH% && c:\tools\cygwin\bin\bash.exe -O expand_aliases ./tests/test.sh
  tags:
    - windowsserver

windows10:
  variables:
    BOWLINE_IMAGE_SUFFIX: "$CI_COMMIT_SHA"
  script:
    - \"$env:ProgramFiles\git\usr\bin\bash.exe\" -O expand_aliases ./tests/test.sh
    - $env:Path = ";C:\tools\cygwin\bin;" + $env:Path
    - c:\tools\cygwin\bin\bash.exe -O expand_aliases ./tests/test.sh
  tags:
    - windows10
