os:
  - linux
  - windows

sudo: required

language: shell

services:
  - docker

before_install:
- pip install docker-compose

script:
- docker-compose.exe version
- docker-compose version
- docker info
- docker run hello-world

