os:
  - linux
  - windows

sudo: required

language: shell

services:
  - docker

before_install:
- |
  (
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      Invoke-WebRequest "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\docker\docker-compose.exe
    fi 
  )

script:
- docker-compose.exe version
- docker-compose version
- docker info
- docker run hello-world

