#!/usr/bin/env bash

BUILD_HELP[selenium]="Build and start selenium containers for testing"
BUILD_HELP_DETAIL[selenium]=" ${BUILD_HELP[selenium]} "

build_command_selenium () {
  echo "# Starting selenium"
  cd .docker/selenium
  # Start the selenium containers
  $FIG up -d --no-recreate
  $FIG ps

  exit 0
}
