#!/usr/bin/env bash

BUILD_HELP[destroy]="Stop and remove project docker containers. Optionally remove image as well."

build_command_destroy () {
  echo "Destroy: This action includes removing the database container and its Drupal database."
  echo "Are you sure you want to stop and remove the containers for this project [Y/n]?"
  read confirm;
  [[ $confirm == 'n' ]] && exit 1;
  $FIG stop; $FIG rm # press y to remove containers
  echo "Do you also want to remove the docker images [Y/n]?"
  read confirm;
  [[ $confirm == 'n' ]] && exit 1;
  docker rmi --no-prune=true ${SLUG}_web
  exit 0;
}
