#!/usr/bin/env bash

BUILD_HELP[help]="Show this help listing. Use help [command] for detailed help."
BUILD_HELP_DETAIL[help]="
  ${BUILD_HELP[help]}
"

build_command_help () {
  if [ "$1" ]; then
    local subcommand=$1
    echo "${subcommand}::${BUILD_HELP_DETAIL[${subcommand}]}" | column -t -s "::"
    exit 0
  fi

  for i in "${!BUILD_HELP[@]}"; do
    echo "${i}::${BUILD_HELP[${i}]}"
  done | column -t -s "::" | sort

  exit 0
}
