#!/usr/bin/env bash

BUILD_HELP[import]="Import the .snapshot.sql.gz file into the database container."
BUILD_HELP_DETAIL[import]="
  ${BUILD_HELP[import]}
"

build_command_import () {
  echo "# BUILDING CONTAINERS"
  # Start containers, build if necessary.
  $FIG up -d --no-recreate
  container=$($FIG ps|grep web|awk '{print $1}')
  # Import snapshot of database
  docker exec -it $container /var/www/scripts/import
}
