#!/usr/bin/env bash

RUN_HELP[preflight]="Preflight checks"
RUN_HELP_DETAIL[preflight]=" ${RUN_HELP[preflight]} "

run_command_preflight () {
  echo "# Pre-flight checks"

  ## 1: Check database.
  table_count=$(mysql -hdbhost -udbuser -pdbpass drupal -ss -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'drupal'")
  if [ $table_count = "0" ]; then
    echo "ERROR: Database empty."
    exit 1
  fi
  echo "Table count: ${table_count}"

  ## 2. Drush
  # @TODO.
  echo "PASS"
  exit 0
}
