#!/usr/bin/env bash

RUN_HELP[help]="Show this help listing. Use help [command] for detailed help."
RUN_HELP_DETAIL[help]=" ${RUN_HELP[help]} "

run_command_help () {
  if [ "$1" ]; then
    local subcommand=$1
    echo "${subcommand}..${RUN_HELP_DETAIL[${subcommand}]}" | column -t -s ".."
    exit 0
  fi

  for i in "${!RUN_HELP[@]}"; do
    echo "${i}..${RUN_HELP[${i}]}"
  done | sort

  exit 0
}
