#!/usr/bin/env bash

cd $(dirname $0)/..
source scripts/include.bash
source scripts/lib/dispatch.sh
declare -A BUILD_HELP
declare -A BUILD_HELP_DETAIL
for subcommand in scripts/subcommands/build_*
  do source $subcommand
done

FIG=${FIG-fig}


# Dispatch the arguments
dispatch build "$@"

echo "# BUILDING CONTAINERS"
echo "Building without importing database. (Run as './scripts/build import' if you need to load the db.)"
# Start containers, build if necessary.
$FIG up -d --no-recreate
container=$($FIG ps|grep web|awk '{print $1}')

# Set up composer.
docker exec -it $container composer self-update
docker exec -it $container composer --working-dir=/var/www install

# Fix file ownership. We set the host user to own everything then give group
# write access to the web server.
docker exec -it $container /var/www/scripts/fix-perms

db_container=$($FIG ps|grep db|awk '{print $1}')
IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' ${container})
DB_IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' ${db_container})

echo "# Fig/docker container status"
$FIG ps

echo ""
echo "# BUILD COMPLETE"
echo "database IP: ${DB_IP}; web IP: ${IP}"
echo "web address: http://${IP}/"
echo ""
echo "  If the above link does not work and you are using Boot2Docker,"
echo "  run the following command then try the link again."
echo "      sudo route -n add 172.17.0.0/16 192.168.59.103"
echo ""


