#!/usr/bin/env bash

# Make sure we are in the scripts directory.
cd $(dirname $0)
source include.bash
[[ $FIG ]] || FIG=fig

# If this isn't the docker container, call this script in the container.
if [ $(pwd) != '/var/www/scripts' ]; then
  cd ..
  container=$($FIG ps|grep web|grep -v Exit|awk '{print $1}')
  if [[ ! $container ]]; then
    # Only run build if container is not running.
    ./scripts/build
    container=$($FIG ps|grep web|grep -v Exit|awk '{print $1}')
  fi
  docker exec -it $container /var/www/scripts/run $@
  exit
fi


#### Pre-flight checks.
if [ $1 = "pre-flight" ]; then
  echo "# Pre-flight checks"

  ## 1: Check database.
  table_count=$(mysql -hdbhost -udbuser -pdbpass drupal -ss -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'drupal'")
  if [ $table_count = "0" ]; then
    echo "ERROR: Database empty."
    exit 1
  fi
  echo "Table count: ${table_count}"

  ## 2. Drush
  # @TODO.
  echo "PASS"
  exit
fi


#### The run steps.
echo -e "\033[32m# RUNNING TESTS\033[m"
cd ..

# Check Drush.
cd docroot
echo -e "\033[34mdrush status:"
../vendor/drush/drush/drush status
echo -e "\033[m"
cd ..

sleep 1

# Run tests.
echo -e "\033[32mRunning tests\033[m"
echo "Cleaning up previous test results."
rm -fv logs/xml/TEST*.xml
PROGRESS_LOG='logs/progress.log'

case "$1" in
  full)
    echo "# Running full test suite"
    ./vendor/behat/behat/bin/behat -f pretty,progress,junit --out ,${PROGRESS_LOG},logs/xml -c tests/behat/smoke.yml
    ;;
  headless)
    echo "# Running headless test suite"
    echo "@TODO"
    ;;
  smoke)
    echo "# Running smoke tests"
    ./vendor/behat/behat/bin/behat -f pretty,progress,junit --out ,${PROGRESS_LOG},logs/xml --tags=@smoke -c tests/behat/smoke.yml
    ;;
  *)
    echo "# Running $1 tests"
    ./vendor/behat/behat/bin/behat -f pretty,progress,junit --out ,${PROGRESS_LOG},logs/xml --tags=@smoke -c tests/behat/smoke.yml
    ;;
esac

EXIT=$?
echo -e "\033[m"
echo Exit Status: $EXIT
exit $EXIT
